name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up C build environment
        uses: actions/setup-cxx@v2
        with:
          compiler: gcc

      - name: Build library
        run: make

      - name: Clean up
        run: make clean
